# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('short_slug', models.SlugField(max_length=8, primary_key=True, serialize=False, verbose_name='Короткий URL')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Короткие URL',
                'verbose_name': 'Короткий URL',
            },
        ),
    ]
